initial_duration=2000
max_response_time=4000
trials=5
iti=2000

criteria_trials = 3
criteria_threshold = 2

# relative to the working directory the app is launched from (the repo root)
correct_image_path=media/greendino.jpg
correct_response_wav=media/correct.wav
incorrect_image_path=media/greenshape.jpg
incorrect_response_wav=media/incorrect.wav

adu_relay=K0