/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_american_weiss_lafayette_io_jni_AduJava */

#ifndef _Included_edu_american_weiss_lafayette_io_jni_AduJava
#define _Included_edu_american_weiss_lafayette_io_jni_AduJava
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: adu */
/*
 * Class:     edu_american_weiss_lafayette_io_jni_AduJava
 * Method:    displayVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_american_weiss_lafayette_io_jni_AduJava_displayVersion
  (JNIEnv *, jobject);

/*
 * Class:     edu_american_weiss_lafayette_io_jni_AduJava
 * Method:    OpenAduDevice
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_edu_american_weiss_lafayette_io_jni_AduJava_OpenAduDevice
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_american_weiss_lafayette_io_jni_AduJava
 * Method:    WriteAduDevice
 * Signature: (ILjava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_edu_american_weiss_lafayette_io_jni_AduJava_WriteAduDevice
  (JNIEnv *, jobject, jint, jstring, jint, jint);

/*
 * Class:     edu_american_weiss_lafayette_io_jni_AduJava
 * Method:    ReadAduDevice
 * Signature: (III)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_american_weiss_lafayette_io_jni_AduJava_ReadAduDevice
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     edu_american_weiss_lafayette_io_jni_AduJava
 * Method:    CloseAduDevice
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_american_weiss_lafayette_io_jni_AduJava_CloseAduDevice
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
